server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Bloque principal de rutas
    location / {
        # Magia Arcana: Intenta buscar el archivo exacto, 
        # si no lo encuentra le agrega .html en secreto, 
        # y si todo falla, redirige al index.
        try_files $uri $uri.html $uri/ /index.html;
    }

    # Bloque de optimización: Guardar assets en caché del navegador (opcional pero recomendado)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}